// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnCHW5UA1djfrsFkkxMUfJJrFKbuPcnXc',
    appId: '1:169125606725:web:ada3a30b870f7fa9123a2c',
    messagingSenderId: '169125606725',
    projectId: 'five-minute-habits',
    authDomain: 'five-minute-habits.firebaseapp.com',
    storageBucket: 'five-minute-habits.firebasestorage.app',
    measurementId: 'G-95GW1Y2MY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOI1ieNZOBJx__ekn-8A9cRy6l8tN5alw',
    appId: '1:169125606725:android:19897fbdc73bb0fd123a2c',
    messagingSenderId: '169125606725',
    projectId: 'five-minute-habits',
    storageBucket: 'five-minute-habits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhYq9x7a2AQouaCzy50WYziWnAgGqnd4M',
    appId: '1:169125606725:ios:d5701c9f10e3a8ae123a2c',
    messagingSenderId: '169125606725',
    projectId: 'five-minute-habits',
    storageBucket: 'five-minute-habits.firebasestorage.app',
    iosClientId: '169125606725-k2tnodcr9pj8p8l3v9m2bnfrkbcba21k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiveMinuteHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhYq9x7a2AQouaCzy50WYziWnAgGqnd4M',
    appId: '1:169125606725:ios:d5701c9f10e3a8ae123a2c',
    messagingSenderId: '169125606725',
    projectId: 'five-minute-habits',
    storageBucket: 'five-minute-habits.firebasestorage.app',
    iosClientId: '169125606725-k2tnodcr9pj8p8l3v9m2bnfrkbcba21k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiveMinuteHabits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnCHW5UA1djfrsFkkxMUfJJrFKbuPcnXc',
    appId: '1:169125606725:web:fa416edda7b75e69123a2c',
    messagingSenderId: '169125606725',
    projectId: 'five-minute-habits',
    authDomain: 'five-minute-habits.firebaseapp.com',
    storageBucket: 'five-minute-habits.firebasestorage.app',
    measurementId: 'G-FHXZPVCLLN',
  );
}
